# Server
server:
  address: localhost
  port: 8080

# Local
spring:
  url: http://localhost:8080

  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/<DB>?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kiziri
    password: Dkiziri232@@

  # JPA
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    encoding: UTF-8

# File Upload location
file:
  upload:
    directory: imageUpload/
    directorylocal: F:/github local/Comprehensive_Project/imageUpload/

# Logger
logging.level:
  org.hibernate.SQL: debug