# Server
server:
  address: localhost
  port: 8080

# Local
spring:
  url: http://localhost:8080

  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    encoding: UTF-8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# File Upload location
#file:
#  upload:
#    directory: imageUpload/
#    directorylocal:

# Logger
logging.level:
  org.hibernate.SQL: debug